In [2]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
arr2d=np.array([[1,2,3,4],[2,3,4,5]])

In [5]:
print(arr2d.shape)
print(arr2d.dtype)

(2, 4)
int64


In [7]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.arange(2,15)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.eye(3)#for identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
newarr=arr2d.astype(np.float64)
newarr.dtype

dtype('float64')

In [16]:
arr2=np.array([[1,1,1,1],[2,2,2,2]])

In [20]:
print("Addition\n",arr2+arr2d,"\n")
print("Substraction\n",arr2-arr2d,"\n")
print("Multipication\n",arr2*arr2d,"\n")
print("Divison\n",arr2/arr2d,"\n")

Addition
 [[2 3 4 5]
 [4 5 6 7]] 

Substraction
 [[ 0 -1 -2 -3]
 [ 0 -1 -2 -3]] 

Multipication
 [[ 1  2  3  4]
 [ 4  6  8 10]] 

Divison
 [[1.         0.5        0.33333333 0.25      ]
 [1.         0.66666667 0.5        0.4       ]] 



In [25]:
print(arr2[1:,2:])

[[2 2]]


In [26]:
arr2.reshape(4,2)

array([[1, 1],
       [1, 1],
       [2, 2],
       [2, 2]])

In [27]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[6,23],[-1,7],[8,9]])
x.dot(y)

array([[ 28,  64],
       [ 67, 181]])

In [30]:
x=np.random.randint(0,21,size=(3,3))
x

array([[ 9, 17, 14],
       [ 6,  4,  0],
       [ 6, 15,  8]], dtype=int32)

In [31]:
y=np.random.randint(0,21,size=(3,3))
y

array([[ 3,  3, 17],
       [ 4,  3, 16],
       [10, 18, 11]], dtype=int32)

In [32]:
print(x+y)

[[12 20 31]
 [10  7 16]
 [16 33 19]]


In [33]:
y*5

array([[15, 15, 85],
       [20, 15, 80],
       [50, 90, 55]], dtype=int32)

In [36]:
np.diff(y)

array([[ 0, 14],
       [-1, 13],
       [ 8, -7]], dtype=int32)

In [37]:
y.std()

np.float64(6.057339186861783)