# **Installing Numpy Modules**

In [ ]:
!pip install numpy

## **Numpy Array Initalization and Properties**

In [ ]:
import numpy as np

**Initalizing with a list**

In [ ]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [ ]:
print("Size=",arr1.size,"\nShape=",arr1.shape,"\nType=",arr1.dtype)

Size= 4 
Shape= (4,) 
Type= int64


**Initalizing with a tuple**

In [ ]:
arr2=np.array(((6.0,7.5,8,9),(2,3,4,5)))
arr2

array([[6. , 7.5, 8. , 9. ],
       [2. , 3. , 4. , 5. ]])

In [ ]:
arr2.reshape(4,2)

array([[6. , 7.5],
       [8. , 9. ],
       [2. , 3. ],
       [4. , 5. ]])

In [ ]:
print("Size=",arr2.size,"\nShape=",arr2.shape,"\nType=",arr2.dtype)

Size= 8 
Shape= (2, 4) 
Type= float64


**Special Initalization Function**

In [ ]:
arrZero=np.zeros((2,4))
arrZero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arrOne=np.ones((4,5))
arrOne

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arrEmpty=np.empty((5,5))
arrEmpty

array([[2.28318827e-315, 0.00000000e+000, 6.51906911e-310,
        6.51906911e-310, 4.90111540e-317],
       [5.33004343e-317, 6.51906911e-310, 6.51906911e-310,
        4.90111540e-317, 5.33004343e-317],
       [6.51906911e-310, 6.51906911e-310, 6.51904245e-310,
        6.51904245e-310, 4.89162934e-317],
       [5.31863644e-317, 4.89162934e-317, 6.51904245e-310,
        6.51906911e-310, 5.31707124e-317],
       [6.51906911e-310, 6.51904245e-310, 6.51904244e-310,
        5.31721353e-317, 1.36757371e-320]])

In [ ]:
arrEye=np.eye(3)#or np.identity(3)
arrEye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arrRange=np.arange(2,17,2)
arrRange

array([ 2,  4,  6,  8, 10, 12, 14, 16])

# **Operations On Numpy Array**

In [ ]:
arr1=np.array([[1,2,3,4],[6,7,8,9]])
arr2=np.array(((6,7,8,9),(2,3,4,5)))

**Basic Operation**

In [ ]:
arr1+arr2

array([[ 7,  9, 11, 13],
       [ 8, 10, 12, 14]])

In [ ]:
arr1*arr2

array([[ 6, 14, 24, 36],
       [12, 21, 32, 45]])

In [ ]:
arr1-arr2

array([[-5, -5, -5, -5],
       [ 4,  4,  4,  4]])

In [ ]:
arr1/arr2

array([[0.16666667, 0.28571429, 0.375     , 0.44444444],
       [3.        , 2.33333333, 2.        , 1.8       ]])

In [ ]:
5*arr1 # same for all other operations

array([[ 5, 10, 15, 20],
       [30, 35, 40, 45]])

In [ ]:
arr1[1,1:]

array([7, 8, 9])

**Conditionl Operations**

In [ ]:
arr1<=5

array([[ True,  True,  True,  True],
       [False, False, False, False]])

In [ ]:
arr2!=6

array([[False,  True,  True,  True],
       [ True,  True,  True,  True]])

**Matrix Multipication**

In [ ]:
arrMul1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arrMul2=np.array([[9,8,7],[6,5,4],[3,2,1]])

In [ ]:
arrMul1.dot(arrMul2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [ ]:
arrMul2.dot(arrMul1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

# **Methods**

**Math Methods**

In [ ]:
arr1=np.array([[1,4,9],[4,5,6],[2,16,9]])
np.sqrt(arr1)

array([[1.        , 2.        , 3.        ],
       [2.        , 2.23606798, 2.44948974],
       [1.41421356, 4.        , 3.        ]])

In [ ]:
arr1=np.array([[1,-2,3],[-4,5,6],[7,-8,9]])
np.abs(arr1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2=np.array([[9,8,7],[6,5,4],[3,2,1]])
np.maximum(arr1,arr2)

array([[9, 8, 7],
       [6, 5, 6],
       [7, 2, 9]])

**Random Methods**

In [ ]:
arr1=np.random.randn(9)
arr1

array([ 0.64520069,  1.74668981,  0.43377395,  0.06604385,  0.42648117,
       -0.33495572,  1.5436648 , -0.49067379, -0.09540247])

In [ ]:
arr1=arr1.reshape(3,3)
arr1=np.ceil(arr1)
arr1

array([[ 1.,  2.,  1.],
       [ 1.,  1., -0.],
       [ 2., -0., -0.]])

In [ ]:
arr2=np.random.randint(1,35,9)
arr2

array([30, 22,  3,  9, 17, 30, 23,  2,  3])