# **Installing Numpy Modules**

In [1]:
!pip install numpy

## **Numpy Array Initalization and Properties**

In [3]:
import numpy as np

**Initalizing with a list**

In [ ]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [ ]:
print("Size=",arr1.size,"\nShape=",arr1.shape,"\nType=",arr1.dtype)

Size= 4 
Shape= (4,) 
Type= int64


**Initalizing with a tuple**

In [ ]:
arr2=np.array(((6.0,7.5,8,9),(2,3,4,5)))
arr2

array([[6. , 7.5, 8. , 9. ],
       [2. , 3. , 4. , 5. ]])

In [ ]:
print("Size=",arr2.size,"\nShape=",arr2.shape,"\nType=",arr2.dtype)

Size= 8 
Shape= (2, 4) 
Type= float64


**Special Initalization Function**

In [ ]:
arrZero=np.zeros((2,4))
arrZero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arrOne=np.ones((4,5))
arrOne

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arrEmpty=np.empty((5,5))
arrEmpty

array([[2.28318827e-315, 0.00000000e+000, 6.51906911e-310,
        6.51906911e-310, 4.90111540e-317],
       [5.33004343e-317, 6.51906911e-310, 6.51906911e-310,
        4.90111540e-317, 5.33004343e-317],
       [6.51906911e-310, 6.51906911e-310, 6.51904245e-310,
        6.51904245e-310, 4.89162934e-317],
       [5.31863644e-317, 4.89162934e-317, 6.51904245e-310,
        6.51906911e-310, 5.31707124e-317],
       [6.51906911e-310, 6.51904245e-310, 6.51904244e-310,
        5.31721353e-317, 1.36757371e-320]])

In [5]:
arrEye=np.eye(3)#or np.identity(3)
arrEye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
arrRange=np.arange(2,17,2)
arrRange

array([ 2,  4,  6,  8, 10, 12, 14, 16])

# **Operations On Numpy Array**

In [12]:
arr1=np.array([[1,2,3,4],[6,7,8,9]])
arr2=np.array(((6,7,8,9),(2,3,4,5)))